In [7]:
import numpy

numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
numpy.array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [8]:
x = numpy.array([[3,6],[5,7]])
y = x.transpose()
print(y)

[[3 5]
 [6 7]]


In [10]:
x = numpy.array([1,2,5])
x[1:2]

array([2])

In [11]:
a = numpy.array([1,2])
b = numpy.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [13]:
a = numpy.array([1,2])
b = numpy.array([3,4,5])
b[a]

array([4, 5])

In [15]:
c = b[1:]
print(b[1:])
b[a] is c

[4 5]


False

In [17]:
x = 20
not numpy.any([x%i == 0 for i in range(2, x)])

False